# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
security:
  #password cf client will use when interacting with broker
  user.password: ${user.password}
hive:
  server.host: ${HIVE_SERVER2_THRIFT_BIND_HOST:localhost}
  server.port: ${HIVE_SERVER2_THRIFT_PORT:10000}
  superuser.name: ${HIVE_SUPERUSER:}
  #path on container where keytab for hive is
  superuser.keytab.path: ${HIVE_SUPERUSER_KEYTAB_PATH:}
  #path on container where configuration for hdfs is
  configuration.path: ${hive.configuration.path:}
  truststore:
    path: ${cloudera.truststore:}
    password: ${cloudera.truststore.password:}
store:
  #optional parameter to configure zookeeper-store
  path: ${broker.store.znode:/broker/hive/metadata}
  user: ${system.user}
  password: ${system.user.password}
  keytabPath: ${system.user.keytab.path}
cf:
  catalog:
    serviceName: ${cf.catalog.servicename:hive}
    serviceId: ${cf.catalog.serviceid:hive}
    serviceDescription: "Hive service allow to access hiveserver2 on hadoop cluster."
    baseId: ${BASE_GUID:}
    plans:
      - id: standard-plan
        name: standard
        description: Creates private HIVE database for a user in org shared space /user/hive/warehouse/
        free: true
    metadata:
      imageUrl: ${IMAGE_URL:}

endpoints.enabled: false
endpoints.health.enabled: true
endpoints.info.enabled: true
endpoints.info.sensitive: false

# http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-application-info-git
management:
  info:
    git:
      mode: full

# http://docs.spring.io/spring-boot/docs/current/reference/html/howto-build.html#howto-build-info
info:
  name: "@project.artifactId@"
  app_version: "@project.version@"
  build:
    group: "@project.groupId@"
    artifact: "@project.artifactId@"
    version: "@project.version@"
    name: "@project.name@"
    time: "@build.time@"
