---
security:
  #password cf client will use when interacting with broker
  user.password: ${user.password}
hive:
  server.host: ${HIVE_SERVER2_THRIFT_BIND_HOST:localhost}
  server.port: ${HIVE_SERVER2_THRIFT_PORT:10000}
  superuser.name: ${HIVE_SUPERUSER:}
  #path on container where keytab for hive is
  superuser.keytab.path: ${HIVE_SUPERUSER_KEYTAB_PATH:}
  #path on container where configuration for hdfs is
  configuration.path: ${hive.configuration.path:}
  truststore:
    path: ${cloudera.truststore:}
    password: ${cloudera.truststore.password:}
store:
  #optional parameter to configure zookeeper-store
  path: ${broker.store.znode:/broker/hive/metadata}
  user: ${system.user}
  password: ${system.user.password}
  keytabPath: ${system.user.keytab.path}
cf:
  catalog:
    serviceName: ${cf.catalog.servicename:hive}
    serviceId: ${cf.catalog.serviceid:hive}
    serviceDescription: "Hive service allow to access hiveserver2 on hadoop cluster."
    baseId: ${BASE_GUID:}
    plans:
      - id: shared-plan
        name: shared
        description: shared
        free: true
      - id: multitenant-plan
        name: multitenant
        description: multitenant
        free: true
    metadata:
      imageUrl: ${IMAGE_URL:}

